---
  - name: Create and run postgres container
    community.docker.docker_container:
      name: vo_pg
      image: postgres
      ports:
      - "5432:5432"
      env:
        POSTGRES_DB: "visualoffice"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "admin"
      volumes:
        - /home/uadmin/docker/volumes/postgres:/var/lib/postgresql/data

  - name: Create and run container with test data to fill database
    community.docker.docker_container:
      name: fill_db
      image: androsovm/fill_db_script:latest
      env:
        DATABASE_HOST: "{{ hostvars['do-04'].ansible_host }}"
    when: fill_database