{
 "title": "VisualOffice-App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average execution time, 5m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[5m])/rate(flask_http_request_duration_seconds_count{status=\"200\"}[5m])"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"200\"}"
    }
   ]
  },
  {
   "title": "Webapp container CPU use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{instance=\"172.28.148.221:8080\",image=\"androsovm/webapp\"}"
    }
   ]
  },
  {
   "title": "Webapp container memory usage, mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"172.28.148.221:8080\",image=\"androsovm/webapp\"}/1024/1024"
    }
   ]
  }
 ]
}