---
  - name: Run VisualOffice-App on one host
    hosts: do-01
    become: true
    vars:
      fill_database: true

    tasks:
      - include_tasks: docker/run_webapp.yml
      - include_tasks: docker/run_reader.yml
      - include_tasks: docker/run_writer.yml
      - include_tasks: docker/run_postgres.yml