---
  - name: Run application in one host
    hosts: do-01
    become: true

    tasks:
      - name: Create VisualOffice-webapp container
        community.docker.docker_container:
          name: vo_webapp
          image: androsovm/webapp
          ports:
          - "8000:8000"
          env:
            READER_HOST: "vo_reader"
            WRITER_HOST: "vo_writer"

      - name: Create VisualOffice-reader container
        community.docker.docker_container:
          name: vo_reader
          image: androsovm/reader
          ports:
          - "8001:8001"
          env:
            DATABASE_HOST: "vo_pg"

      - name: Create VisualOffice-writer container
        community.docker.docker_container:
          name: vo_writer
          image: androsovm/writer
          ports:
          - "8002:8002"
          env:
            DATABASE_HOST: "vo_pg"

      - name: Create postgres container
        community.docker.docker_container:
          name: vo_pg
          image: postgres
          ports:
          - "5432:5432"
          env:
            POSTGRES_DB: "visualoffice"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
          volumes:
            - /home/uadmin/docker/volumes/postgres:/var/lib/postgresql/data