---
- name: Run dockprom docker-compose
  hosts: do-05
  become: true    
  tasks:

  - name: Git checkout Dockprom
    ansible.builtin.git:
      repo: 'https://github.com/stefanprodan/dockprom'
      dest: "/home/uadmin/dockprom"
      version: v4.7.2
    ignore_errors: yes

  - name: Copy prometheus.yml
    ansible.builtin.copy:
      src: dockprom/prometheus.yml
      dest: /home/uadmin/dockprom/prometheus/prometheus.yml
      mode: '755'

  - name: Run Dockprom services
    community.docker.docker_compose:
      project_src: "/home/uadmin/dockprom"

- hosts: all:!do-05
  become: true
  tasks:
    - name: Run exporters on all hosts
      include_tasks: dockprom/run_metrics.yml
