---
  - name: Get hostvars postgres_host if exist
    set_fact: 
      postgres_host: "{{ hostvars['do-04'].ansible_host }}"
    ignore_errors: yes

  - name: Create and run VisualOffice-writer container
    community.docker.docker_container:
      name: '{{writer_container_name}}'
      image: '{{writer_image}}:{{writer_image_ver}}'
      ports:
      - "8002:8002"
      env:
        DATABASE_HOST: "{{ postgres_container_name if postgres_host is undefined 
                           else postgres_host }}"