---    
  - name: Create a dockprom-exporters directory 
    ansible.builtin.file:
      path: "/home/uadmin/dockprom-exporters"
      state: directory
      mode: '0755'      
  
  - name: Download docker-compose dockprom-exporters file
    get_url:
      url: https://raw.githubusercontent.com/stefanprodan/dockprom/v4.7.2/docker-compose.exporters.yml
      dest: "/home/uadmin/dockprom-exporters/docker-compose.yml"
      mode: '0755'      
  
  - name: Create and start exporters services
    community.docker.docker_compose:
      project_src: "/home/uadmin/dockprom-exporters"
