# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Infra

on:
  push:
    branches: [ main ]

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:

    - name: Git clone repo
      uses: actions/checkout@v2

    - name: Lint Ansible Docker Run Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          VisualOffice-Infra/ansible/playbooks/docker/run_multihost.yml
          VisualOffice-Infra/ansible/playbooks/docker/run_compose.yml
          VisualOffice-Infra/ansible/playbooks/docker/run_standalone.yml

    - name: Lint Ansible Docker Tasks
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          VisualOffice-Infra/ansible/playbooks/docker/install_docker.yml
          VisualOffice-Infra/ansible/playbooks/docker/run_postgres.yml
          VisualOffice-Infra/ansible/playbooks/docker/run_reader.yml
          VisualOffice-Infra/ansible/playbooks/docker/run_webapp.yml
          VisualOffice-Infra/ansible/playbooks/docker/run_writer.yml