# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Infra

on:
  push:
    branches: [ main ]

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    steps:

    - name: Git clone repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Install ansible-lint
      run: pip install ansible-lint

    - name: Lint docker playbooks
      run: |
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/run_multihost.yml
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/run_compose.yml
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/run_standalone.yml

    - name: Lint docker tasks
      run: |
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/install_docker.yml
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/run_postgres.yml
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/run_reader.yml
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/run_webapp.yml
          ansible-lint VisualOffice-Infra/ansible/playbooks/docker/run_writer.yml